services:
  frontendfk:
    container_name: frontendfk
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3500:3000"
    networks:
      - SMARTDATA

networks:
  SMARTDATA:
    external: true