services:
  frontendfk:
    container_name: frontendfk
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        # URL del backend y clave de cifrado para Next (inyectadas en build)
        NEXT_PUBLIC_URL_BACK: https://lazzyfact.datasmartify.com
        NEXT_PUBLIC_KEY_CRYPTO: una-clave-segura-y-larga-2025
    ports:
      - "3500:3000"
    environment:
      # También disponibles en runtime (útil para diagnósticos)
      NEXT_PUBLIC_URL_BACK: https://lazzyfact.datasmartify.com
      NEXT_PUBLIC_KEY_CRYPTO: una-clave-segura-y-larga-2025
    networks:
      - SMARTDATA

networks:
  SMARTDATA:
    external: true